id: I29D4E954
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 14:35:33.243189+00:00
last_modified: 2022-12-14 14:35:33.243202+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-072-008
  eft-text-version: 1.22.3 2020
  title: Toh_308-Questions_Regarding_Death_and_Transmigration-v2
bases:
  7B93:
    source_metadata: null
    order: 1
    base_file: 7B93.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
